dist: trusty
language: ruby
cache: bundler
sudo: false
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
script:
  - bundle exec rubocop
  - bundle exec rspec spec
jdk:
  - oraclejdk8
rvm:
  - jruby
